### ISSUE TITLE
Duplicate configuration in `config.yaml`

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#25]
Currently, we need to define the following for the all machines:

```yml
machines:
  - id: m1
    enabled: !!bool true
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy_type: l99.driver.fanuc.collectors.UseCase01, fanuc
    handler_type: l99.driver.fanuc.handlers.Native, fanuc
    sweep_ms: !!int 1000
    net_ip: 1.2.3.4
    net_port: !!int 8193
    net_timeout_s: !!int 10
    broker:
      enabled: !!bool true
      net_ip: localhost
      net_port: !!int 1883
      auto_connect: !!bool true
      publish_status: !!bool true
      publish_arrivals: !!bool false
      publish_changes: !!bool true
      publish_disco: !!bool true
      disco_base_topic: fanuc
```

It is good if we connect to a single machine, but what about (e.g.) 10 machines? I think that the broker configuration should be put outside of the `machines` object, like so:

```yml
broker:
  enabled: !!bool true
  net_ip: localhost
  net_port: !!int 1883
  auto_connect: !!bool true
  publish_status: !!bool true
  publish_arrivals: !!bool false
  publish_changes: !!bool true
  publish_disco: !!bool true
  disco_base_topic: fanuc
machines:
  - id: m1
    enabled: !!bool true
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy_type: l99.driver.fanuc.collectors.UseCase01, fanuc
    handler_type: l99.driver.fanuc.handlers.Native, fanuc
    sweep_ms: !!int 1000
    net_ip: 1.2.3.4
    net_port: !!int 8193
    net_timeout_s: !!int 10
```

---

It might be also a good idea to allow multiple configuration or even watching for them.

Let me explain my use case: I need to be able toggle monitoring on and off for every machine individually. Currently, I need to update the `config.yaml` (add or toggle `enabled` / remove / comment out the particular machine in `config.yaml`) and restart `fanuc-driver`.

It might be a good idea to have a _folder_ for config files where one file would be used for the broker configuration and there would be also one file per machine. `fanuc-driver` would watch those files, e.g. when a machine is added, it would start its monitoring, or when a config of a particular machine is removed OR `enabled` set to `false`, `fanuc-driver` would stop getting data from that particular machine.

What do you think?
