### ISSUE TITLE
Constructor on type l99.driver.fanuc.FanucMachine not found

### ISSUE THREAD

**Issue by elliskot** [Ladder99/fanuc-driver#78]
Hi, when start service I get this error: **Constructor on type 'l99.driver.fanuc.FanucMachine' not found**. I don't understand where is the problem.
Fanuc-driver is last commit (de0e822a) on main branch, and this is the my config:

```
user:
  # focas sources
  source-1: &source-1
    # example fanuc source
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: 1000
      net:
        ip: 192.168.2.202
        port: 8193
        timeout_s: 3
  # collectors
  collector-0: &collector-0
    # example collector
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      - l99.driver.fanuc.collectors.ParameterDump, fanuc
      - l99.driver.fanuc.collectors.DiagnosisDump, fanuc
      - l99.driver.fanuc.collectors.PmcDump, fanuc
  collector-1: &collector-1
    # example collector
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
  # targets
  target-null: &target-null
    # send to nothing
    << : *transport-base-null
    l99.driver.fanuc.transports.Null, fanuc:
      enabled: true
  target-mqtt-1: &target-mqtt-1
    # send to tcp mqtt broker
    << : *transport-base-mqtt
    l99.driver.fanuc.transports.MQTT, fanuc:
      << : *default-mqtt-options
      enabled: true
      net:
        type: tcp
        ip: localhost
        port: 1883
      anonymous: true
      user:
      password:
  target-mqtt-2: &target-mqtt-2
    # send to websocket mqtt broker
    << : *transport-base-mqtt
    l99.driver.fanuc.transports.MQTT, fanuc:
      << : *default-mqtt-options
      enabled: true
      net:
        type: ws
        ip: test.mosquitto.org
        port: 8080
      anonymous: true
      user:
      password:
  target-spb-1: &target-spb-1
    # send to tcp mqtt broker
    << : *transport-base-spb
    l99.driver.fanuc.transports.SpB, fanuc:
      enabled: true
      net:
        type: tcp
        ip: 10.1.10.2
        port: 1883
      anonymous: false
      user: admin
      password: password
  target-shdr-1: &target-shdr-1
    # open tcp socket for mtconnect agent
    << : *transport-base-shdr
    l99.driver.fanuc.transports.SHDR, fanuc:
      << : *default-shdr-transformers
      << : *default-shdr-model-genny
      device_name: f_sim
      net:
        port: 7878
        heartbeat_ms: 10000
        interval_ms: 1000
```

thanks
Ellis
